import type { UserWithProfile } from "@/lib/types";

export const mockUsers: UserWithProfile[] = [
  // ===== FAMILIES =====
  {
    id: "user-1",
    email: "sophie@email.com",
    name: "Sophie Martin",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie",
    bio: "Maman d'un petit garcon en fauteuil roulant, toujours a la recherche d'activites adaptees en Ile-de-France.",
    role: "FAMILY",
    createdAt: "2025-03-15T10:30:00.000Z",
    familyProfile: {
      id: "fp-1",
      userId: "user-1",
      handicapTypes: ["MOTEUR"],
      personConcerned: "CHILD",
      city: "Paris",
      department: "75",
      region: "Ile-de-France",
      childAge: 8,
      familyComposition: "Maman solo avec un enfant",
    },
  },
  {
    id: "user-2",
    email: "karim@email.com",
    name: "Karim Benhadi",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Karim",
    bio: "Papa d'une ado sourde, passionne par le sport adapte et la communaute.",
    role: "FAMILY",
    createdAt: "2025-04-02T14:15:00.000Z",
    familyProfile: {
      id: "fp-2",
      userId: "user-2",
      handicapTypes: ["AUDITIF"],
      personConcerned: "CHILD",
      city: "Marseille",
      department: "13",
      region: "PACA",
      childAge: 12,
      familyComposition: "Couple avec deux enfants",
    },
  },
  {
    id: "user-3",
    email: "claire@email.com",
    name: "Claire Dubois",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Claire",
    bio: "En quete de lieux accueillants pour notre famille. Chaque sortie est une aventure!",
    role: "FAMILY",
    createdAt: "2025-05-20T08:45:00.000Z",
    familyProfile: {
      id: "fp-3",
      userId: "user-3",
      handicapTypes: ["POLYHANDICAP"],
      personConcerned: "CHILD",
      city: "Lyon",
      department: "69",
      region: "Auvergne-Rhone-Alpes",
      childAge: 5,
      familyComposition: "Couple avec un enfant",
    },
  },
  {
    id: "user-4",
    email: "thomas@email.com",
    name: "Thomas Petit",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Thomas",
    bio: "Passionne de culture accessible et de sorties en famille avec mon fils.",
    role: "FAMILY",
    createdAt: "2025-06-10T16:00:00.000Z",
    familyProfile: {
      id: "fp-4",
      userId: "user-4",
      handicapTypes: ["VISUEL"],
      personConcerned: "CHILD",
      city: "Toulouse",
      department: "31",
      region: "Occitanie",
      childAge: 10,
      familyComposition: "Couple avec trois enfants",
    },
  },
  {
    id: "user-5",
    email: "amina@email.com",
    name: "Amina Diallo",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amina",
    bio: "Accompagnante d'un ado extraordinaire, je partage nos decouvertes.",
    role: "FAMILY",
    createdAt: "2025-07-01T11:20:00.000Z",
    familyProfile: {
      id: "fp-5",
      userId: "user-5",
      handicapTypes: ["PSYCHIQUE"],
      personConcerned: "CHILD",
      city: "Bordeaux",
      department: "33",
      region: "Nouvelle-Aquitaine",
      childAge: 15,
      familyComposition: "Famille recomposee avec deux enfants",
    },
  },

  // ===== BUSINESSES =====
  {
    id: "user-6",
    email: "contact@ecuries-du-soleil.fr",
    name: "Les Ecuries du Soleil",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ecuries",
    bio: "Centre equestre adapte proposant des seances d'equitherapie et d'equitation adaptee pour enfants et adultes en situation de handicap. Notre equipe de moniteurs diplomes accueille chaque cavalier avec bienveillance.",
    role: "BUSINESS",
    createdAt: "2025-02-10T09:00:00.000Z",
    businessProfile: {
      id: "bp-1",
      userId: "user-6",
      companyName: "Les Ecuries du Soleil",
      siret: "84726391500014",
      description:
        "Situe au coeur de la Provence, notre centre equestre est entierement adapte aux personnes en situation de handicap moteur et cognitif. Nous proposons des seances d'equitherapie encadrees par des professionnels diplomes d'Etat, dans un environnement calme et securise. Nos installations comprennent un manege couvert accessible, des rampes de montoir adaptees et une ecurie de plain-pied.",
      website: "https://www.ecuries-du-soleil.fr",
      address: "Chemin des Oliviers, 13100 Aix-en-Provence",
      city: "Aix-en-Provence",
      department: "13",
      handicapTypesSupported: ["MOTEUR", "COGNITIF"],
      categories: ["sport"],
      photos: [
        "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800",
        "https://images.unsplash.com/photo-1509460913899-515f1df34fea?w=800",
      ],
      isVerified: true,
      averageRating: 5.0,
      totalReviews: 1,
    },
  },
  {
    id: "user-7",
    email: "accueil@musee-tactile-lyon.fr",
    name: "Musee Tactile de Lyon",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Musee",
    bio: "Premier musee entierement tactile de la region lyonnaise, dedie a l'art et a la decouverte sensorielle pour tous les publics.",
    role: "BUSINESS",
    createdAt: "2025-01-20T10:30:00.000Z",
    businessProfile: {
      id: "bp-2",
      userId: "user-7",
      companyName: "Musee Tactile de Lyon",
      siret: "79153824600021",
      description:
        "Le Musee Tactile de Lyon est un espace culturel unique ou chaque oeuvre est concue pour etre touchee et exploree par tous les sens. Nos visites guidees sont proposees en langue des signes francaise et en audiodescription. Des maquettes tactiles, des reproductions en relief et des dispositifs sonores permettent a chacun de vivre une experience culturelle riche et inclusive.",
      website: "https://www.musee-tactile-lyon.fr",
      address: "12 rue de la Republique, 69002 Lyon",
      city: "Lyon",
      department: "69",
      handicapTypesSupported: ["VISUEL", "AUDITIF"],
      categories: ["culture"],
      photos: [
        "https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=800",
      ],
      isVerified: true,
      averageRating: 4.0,
      totalReviews: 1,
    },
  },
  {
    id: "user-8",
    email: "info@aquaadapt.fr",
    name: "AquaAdapt",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=AquaAdapt",
    bio: "Centre aquatique adapte a Paris, proposant des cours de natation et d'aquagym pour tous les types de handicap.",
    role: "BUSINESS",
    createdAt: "2025-03-05T13:45:00.000Z",
    businessProfile: {
      id: "bp-3",
      userId: "user-8",
      companyName: "AquaAdapt",
      siret: "91234567800015",
      description:
        "AquaAdapt est le premier centre aquatique parisien entierement dedie a l'accessibilite. Notre bassin est equipe de rampes immergees, de fauteuils de mise a l'eau et de systemes de boucle magnetique. Nos maitres-nageurs sont tous formes a l'accompagnement des personnes en situation de handicap, quel que soit le type de deficience. Nous proposons des cours individuels et collectifs adaptes, de l'eveil aquatique au perfectionnement.",
      website: "https://www.aquaadapt.fr",
      address: "45 avenue de la Grande Armee, 75016 Paris",
      city: "Paris",
      department: "75",
      handicapTypesSupported: [
        "MOTEUR",
        "VISUEL",
        "AUDITIF",
        "MENTAL",
        "PSYCHIQUE",
        "COGNITIF",
        "POLYHANDICAP",
      ],
      categories: ["sport"],
      photos: [
        "https://images.unsplash.com/photo-1576610616656-d3aa5d1f4534?w=800",
        "https://images.unsplash.com/photo-1600965962361-9035dbfd1c50?w=800",
      ],
      isVerified: true,
      averageRating: 4.0,
      totalReviews: 1,
    },
  },
  {
    id: "user-9",
    email: "bonjour@jardin-sensoriel.fr",
    name: "Le Jardin Sensoriel",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jardin",
    bio: "Jardin therapeutique et sensoriel a Nantes, concu pour stimuler les sens et favoriser le bien-etre des personnes en situation de handicap.",
    role: "BUSINESS",
    createdAt: "2025-04-18T07:30:00.000Z",
    businessProfile: {
      id: "bp-4",
      userId: "user-9",
      companyName: "Le Jardin Sensoriel",
      siret: "82345678900028",
      description:
        "Le Jardin Sensoriel est un espace vert therapeutique de 3 000 m2 au coeur de Nantes. Nos parcours sensoriels sont concu pour eveiller le toucher, l'odorat, l'ouie et le gout a travers des plantations aromatiques, des fontaines sonores, des textures variees et des espaces de detente. Des ateliers de jardinage adapte sont proposes tout au long de l'annee, encadres par des educateurs specialises et des horticulteurs passionnes.",
      website: "https://www.jardin-sensoriel.fr",
      address: "8 allee des Magnolias, 44000 Nantes",
      city: "Nantes",
      department: "44",
      handicapTypesSupported: ["VISUEL", "COGNITIF", "PSYCHIQUE"],
      categories: ["loisirs"],
      photos: [
        "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
      ],
      isVerified: true,
      averageRating: 3.0,
      totalReviews: 1,
    },
  },
  {
    id: "user-10",
    email: "hello@techkids-accessible.fr",
    name: "TechKids Accessible",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=TechKids",
    bio: "Ateliers de robotique et de programmation adaptes aux enfants en situation de handicap a Bordeaux.",
    role: "BUSINESS",
    createdAt: "2025-08-22T15:00:00.000Z",
    businessProfile: {
      id: "bp-5",
      userId: "user-10",
      companyName: "TechKids Accessible",
      siret: "53987612400032",
      description:
        "TechKids Accessible propose des ateliers de robotique, de programmation et de creation numerique specialement concu pour les enfants en situation de handicap moteur et auditif. Nos locaux sont entierement accessibles et nos animateurs sont formes a la communication en LSF. Nous utilisons du materiel adapte (claviers ergonomiques, interfaces tactiles, robots programmables accessibles) pour permettre a chaque enfant de decouvrir le numerique a son rythme.",
      website: "https://www.techkids-accessible.fr",
      address: "22 cours de l'Intendance, 33000 Bordeaux",
      city: "Bordeaux",
      department: "33",
      handicapTypesSupported: ["MOTEUR", "AUDITIF"],
      categories: ["education"],
      photos: [
        "https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?w=800",
      ],
      isVerified: false,
      averageRating: 2.0,
      totalReviews: 1,
    },
  },
];
